import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {NavigationBar, FooterPart} from "../components/menu"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Moment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <header>
        <NavigationBar/>
      </header>
      {children}
      <footer>
        <FooterPart/>
      </footer>
      </body>
    </html>
  );
}
