# Generated by Django 6.1.1 on 2026-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sound",
            name="title",
            field=models.CharField(unique=True),
        ),
    ]
