# Generated by Django 6.1.1 on 2026-09-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_sound_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="sound",
            name="description",
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name="sound",
            name="picture",
            field=models.ImageField(default="", upload_to="pictures"),
            preserve_default=False,
        ),
    ]
