# Generated by Django 6.1.1 on 2026-09-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sound_description_sound_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sound",
            name="picture",
        ),
    ]
