# Generated by Django 6.1.1 on 2026-09-11 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_sound_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sound",
            name="audio",
            field=models.FileField(
                upload_to="sounds",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp3", "ogg"])
                ],
            ),
        ),
    ]
